
import {
    IconArticle,
    IconBook,
    IconBook2,
    IconBrackets,
    IconBrandBlogger,
    IconBrandX,
    IconCertificate,
    IconFileAnalytics,
    IconFileText,
    IconGitBranch,
    IconMail,
    IconMicrophone,
    IconPresentation,
    IconSchool,
    IconVideo,
  } from '@tabler/icons-react';
  
export const CONTENT_TYPES = [
  {
    value: 'blog',
    label: 'Blog Post',
    icon: IconBrandBlogger,
    description: 'Create engaging blog content',
    categories: ['marketing', 'devrel', 'technical'],
  },
  {
    value: 'documentation',
    label: 'Documentation',
    icon: IconBook,
    description: 'Technical documentation and guides',
    categories: ['technical', 'devrel'],
  },
  {
    value: 'article',
    label: 'Article',
    icon: IconArticle,
    description: 'In-depth articles and analysis',
    categories: ['marketing', 'technical', 'devrel'],
  },
  {
    value: 'tutorial',
    label: 'Tutorial',
    icon: IconSchool,
    description: 'Step-by-step learning guides',
    categories: ['technical', 'devrel', 'video'],
  },
  {
    value: 'podcast-script',
    label: 'Podcast Script',
    icon: IconMicrophone,
    description: 'Engaging audio content scripts',
    categories: ['audio', 'marketing'],
    disabled: true,
  },
  {
    value: 'video_tutorial',
    label: 'Video Tutorial',
    icon: IconVideo,
    description: 'Technical screencasts & demos',
    categories: ['video', 'technical', 'devrel'],
  },
  {
    value: 'presentation',
    label: 'Presentation',
    icon: IconPresentation,
    description: 'Slide decks & speaking notes',
    categories: ['marketing', 'devrel'],
  },
  {
    value: 'newsletter',
    label: 'Newsletter',
    icon: IconMail,
    description: 'Email content & updates',
    categories: ['marketing', 'social'],
  },
  {
    value: 'social',
    label: 'Social Post',
    icon: IconBrandX,
    description: 'Platform-optimized content',
    categories: ['marketing', 'social', 'devrel'],
  },
  {
    value: 'release_notes',
    label: 'Release Notes',
    icon: IconGitBranch,
    description: 'Product updates & changes',
    categories: ['technical', 'devrel'],
  },
  {
    value: 'case_study',
    label: 'Case Study',
    icon: IconFileAnalytics,
    description: 'Success stories & analysis',
    categories: ['marketing', 'technical'],
  },
  {
    value: 'whitepaper',
    label: 'Whitepaper',
    icon: IconFileText,
    description: 'Professional whitepapers',
    categories: ['marketing', 'technical'],
  },
  {
    value: 'api_doc',
    label: 'API Doc',
    icon: IconBrackets,
    description: 'API documentation & references',
    categories: ['technical', 'devrel'],
  },
  {
    value: 'course',
    label: 'Course',
    icon: IconCertificate,
    description: 'Educational content structure',
    categories: ['technical', 'devrel', 'video'],
    disabled: true,
  },
  {
    value: 'ebook',
    label: 'eBook',
    icon: IconBook2,
    description: 'Long-form digital books',
    categories: ['marketing', 'technical', 'devrel'],
    disabled: true,
  },
  {
    value: 'podcast',
    label: 'Podcast',
    icon: IconMicrophone,
    description: 'Expand your ideas into engaging podcast about any topics in minutes',
    categories: ['audio', 'marketing', 'devrel'],
    disabled: true,
  },
  {
    value: 'reel',
    label: 'Social Media Reel',
    icon: IconVideo,
    description: 'Create short, attention-grabbing social media content from your ideas',
    categories: ['video', 'social', 'marketing'],
    disabled: true,
  },
];

export const CONTENT_CATEGORIES = [
  { value: 'marketing', label: 'Marketing' },
  { value: 'devrel', label: 'DevRel' },
  { value: 'social', label: 'Social Media' },
  { value: 'audio', label: 'Audio' },
  { value: 'video', label: 'Video' },
  { value: 'technical', label: 'Technical' },
];

  export const getStructuredBlocks = (type: string, idea: string) => {
    const structures = {
      blog: [
        {
          id: 1,
          title: 'Introduction',
          content: '',
          description: 'Set the context and hook the reader with a compelling opening that introduces your main topic.',
          comments: [],
        },
        {
          id: 2,
          title: 'Main Content',
          content: '',
          description: 'Develop your key points with supporting evidence and examples.',
          comments: [],
        },
        {
          id: 3,
          title: 'Conclusion',
          content: '',
          description: 'Summarize key points and provide actionable insights or final thoughts.',
          comments: [],
        },
      ],
      documentation: [
        {
          id: 1,
          title: 'Overview',
          content: '',
          description: 'Provide a high-level introduction to the system or feature being documented.',
          comments: [],
        },
        {
          id: 2,
          title: 'Getting Started',
          content: '',
          description: 'Guide users through initial setup and basic usage with clear, step-by-step instructions.',
          comments: [],
        },
        {
          id: 3,
          title: 'Core Concepts',
          content: '',
          description: 'Explain fundamental concepts and terminology essential for understanding the system.',
          comments: [],
        },
        {
          id: 4,
          title: 'Advanced Usage',
          content: '',
          description: 'Cover complex features and advanced implementation scenarios.',
          comments: [],
        },
        {
          id: 5,
          title: 'Troubleshooting',
          content: '',
          description: 'Address common issues and provide solutions to typical problems.',
          comments: [],
        },
      ],
      article: [
        {
          id: 1,
          title: 'Executive Summary',
          content: '',
          description: 'Provide a brief overview of the main points and key findings.',
          comments: [],
        },
        {
          id: 2,
          title: 'Background',
          content: '',
          description: 'Present relevant context and historical information about the topic.',
          comments: [],
        },
        {
          id: 3,
          title: 'Analysis',
          content: '',
          description: 'Examine the topic in detail, including data, research, and expert insights.',
          comments: [],
        },
        {
          id: 4,
          title: 'Key Findings',
          content: '',
          description: 'Highlight the most important discoveries and conclusions from the analysis.',
          comments: [],
        },
        {
          id: 5,
          title: 'Recommendations',
          content: '',
          description: 'Provide actionable suggestions based on the analysis and findings.',
          comments: [],
        },
      ],
      tutorial: [
        {
          id: 1,
          title: 'Prerequisites',
          content: '',
          description: 'List required knowledge, tools, and setup needed for this tutorial.',
          comments: [],
        },
        {
          id: 2,
          title: 'Introduction',
          content: '',
          description: `Explain what will be learned and why it's important.`,
          comments: [],
        },
        {
          id: 3,
          title: 'Step-by-Step Guide',
          content: '',
          description: 'Detailed instructions with code examples and explanations.',
          comments: [],
        },
        {
          id: 4,
          title: 'Common Issues',
          content: '',
          description: 'Address potential problems and their solutions.',
          comments: [],
        },
        {
          id: 5,
          title: 'Next Steps',
          content: '',
          description: 'Suggest further learning resources and advanced topics.',
          comments: [],
        },
      ],
      'podcast-script': [
        {
          id: 1,
          title: 'Show Introduction',
          content: '',
          description: 'Opening hooks and episode overview.',
          comments: [],
        },
        {
          id: 2,
          title: 'Topic Introduction',
          content: '',
          description: 'Present the main topic and its relevance.',
          comments: [],
        },
        {
          id: 3,
          title: 'Main Discussion Points',
          content: '',
          description: 'Key talking points and insights.',
          comments: [],
        },
        {
          id: 4,
          title: 'Guest Questions',
          content: '',
          description: 'Interview questions or discussion prompts.',
          comments: [],
        },
        {
          id: 5,
          title: 'Wrap-up',
          content: '',
          description: 'Summary and call-to-action.',
          comments: [],
        },
      ],
      video_tutorial: [
        {
          id: 1,
          title: 'Video Introduction',
          content: '',
          description: 'Hook and overview of what will be covered.',
          comments: [],
        },
        {
          id: 2,
          title: 'Setup Instructions',
          content: '',
          description: 'Environment setup and prerequisites.',
          comments: [],
        },
        {
          id: 3,
          title: 'Main Content',
          content: '',
          description: 'Step-by-step demonstration with explanations.',
          comments: [],
        },
        {
          id: 4,
          title: 'Common Pitfalls',
          content: '',
          description: 'Addressing common mistakes and solutions.',
          comments: [],
        },
        {
          id: 5,
          title: 'Conclusion',
          content: '',
          description: 'Recap and next steps.',
          comments: [],
        },
      ],
      presentation: [
        {
          id: 1,
          title: 'Title Slide',
          content: '',
          description: 'Presentation title, speaker info, and hook.',
          comments: [],
        },
        {
          id: 2,
          title: 'Agenda',
          content: '',
          description: 'Overview of topics to be covered.',
          comments: [],
        },
        {
          id: 3,
          title: 'Main Content',
          content: '',
          description: 'Key points with supporting visuals.',
          comments: [],
        },
        {
          id: 4,
          title: 'Demo/Examples',
          content: '',
          description: 'Practical demonstrations or case studies.',
          comments: [],
        },
        {
          id: 5,
          title: 'Q&A and Resources',
          content: '',
          description: 'Discussion points and additional materials.',
          comments: [],
        },
      ],
      newsletter: [
        {
          id: 1,
          title: 'Header',
          content: '',
          description: 'Newsletter title and issue highlights.',
          comments: [],
        },
        {
          id: 2,
          title: 'Main Story',
          content: '',
          description: 'Featured article or primary content.',
          comments: [],
        },
        {
          id: 3,
          title: 'News Roundup',
          content: '',
          description: 'Additional news items and updates.',
          comments: [],
        },
        {
          id: 4,
          title: 'Resources',
          content: '',
          description: 'Useful links and recommended content.',
          comments: [],
        },
        {
          id: 5,
          title: 'Call-to-Action',
          content: '',
          description: 'Engagement prompts and contact information.',
          comments: [],
        },
      ],
      api_doc: [
        {
          id: 1,
          title: 'API Overview',
          content: '',
          description: 'Introduction to the API and its purpose.',
          comments: [],
        },
        {
          id: 2,
          title: 'Authentication',
          content: '',
          description: 'Security requirements and token handling.',
          comments: [],
        },
        {
          id: 3,
          title: 'Endpoints',
          content: '',
          description: 'Detailed endpoint documentation with examples.',
          comments: [],
        },
        {
          id: 4,
          title: 'Request/Response Examples',
          content: '',
          description: 'Sample API calls and responses.',
          comments: [],
        },
        {
          id: 5,
          title: 'Error Handling',
          content: '',
          description: 'Common errors and troubleshooting.',
          comments: [],
        },
      ],
    };
  
    return (
      structures[type as keyof typeof structures] || [
        {
          id: 1,
          title: 'Content',
          content: '',
          description: 'Add your content here...',
          comments: [],
        },
      ]
    );
  };
